### ISSUE TITLE
"hello world" app again doesn't quit when I close its window 

### ISSUE THREAD

**Issue by mykmelez** [mozilla/positron#38]
@jryans After merging from upstream in #37, Hello World again doesn't quit when I close its window, so upstream appears to have regressed your fix for #29.

**Comment by jryans** [comment]
Okay, I'll take a look!

**Comment by jryans** [comment]
I checked Linux tonight and it seems to be working. I'll take a look at Windows tomorrow. @mykmelez, what OS were you testing?

**Comment by mykmelez** [comment]
I'm testing on Mac!

**Comment by jryans** [comment]
@mykmelez, I thought it's not supposed to quit on Mac though? Maybe I am forgetting what it did before... The test app skips quitting on Mac I thought: https://github.com/mozilla/positron/blob/master/positron/test/hello-world/main.js#L11-L18

**Comment by mykmelez** [comment]
OMG, of course. 🐑ish, :chagrined:, :contrite:, where are all the complex-emotion emoji when you need them? Sorry for wasting your time, @jryans!

**Comment by jryans** [comment]
No worries, it's kind of confusing! 😄
